#!/usr/bin/env python3
"""vtasm_dma.rom -> checked-in C header for the DMA-card firmware.

The blob is [4096B font (NORMAL.CHR minus its 128B header)] ++ [ROM-build
viaterm_dma image]; the boot ROM's F4 stub (Stage 3) streams it verbatim to
0:0C80.  console/mgmt_con.c serves it on the 0x1C download command.  The array
is placed in flash (__in_flash) so the copy_to_ram firmware image doesn't pay
SRAM for it; core0 alone reads it, at leisure.

Symbol names (VTASM_BLOB_LEN / vtasm_blob) match v9k_flop's vtasm_blob.h so the
console/test code ports mechanically.
"""
import sys

src, dst = sys.argv[1], sys.argv[2]
data = open(src, "rb").read()

with open(dst, "w") as f:
    f.write("/* Generated by victor_client/gen_blob.py -- do not edit.\n"
            " * Rebuild with `./build.sh` in victor_client/ (needs nasm; header\n"
            " * is checked in so the firmware build itself never does).\n"
            " * Layout: 4096B full font (NORMAL.CHR) ++ ROM-build viaterm_dma\n"
            " * image; served raw by console/mgmt_con.c on the 0x1C command. */\n"
            "#pragma once\n"
            "#include <stdint.h>\n"
            "#ifndef __in_flash              /* host tests: no pico SDK */\n"
            "#define __in_flash(group)\n"
            "#endif\n\n")
    f.write("#define VTASM_BLOB_LEN %du\n\n" % len(data))
    f.write('static const uint8_t vtasm_blob[VTASM_BLOB_LEN] __in_flash("vtasm_blob") = {\n')
    for i in range(0, len(data), 16):
        f.write("    " + ",".join("0x%02x" % b for b in data[i:i+16]) + ",\n")
    f.write("};\n")

print("%s: %d bytes -> %s" % (src, len(data), dst))
